security:
  oauth2:
    client:
      registration:
        google:
          client-id: 34833222814-tpmp56gqba8k9mkrg23dpivi3bl8dlvp.apps.googleusercontent.com
          clientSecret: i6Xp9lTMeSRRbmTLDzRROl2B
          scope:
            - email
            - profile